// ====================================================================
// WORDING POOLS สำหรับ PO Fields
// ====================================================================

import { limitAndCleanEN, limitAndCleanTH, pickRandom } from './helpers/poUtilities.core';

const fillField = (selector: string, text: string) => cy.get(selector).clear().type(text);

const fillBilingual = (
  enSel: string, thSel: string,
  enPool: string[], thPool: string[],
  enLim: number, thLim: number
) => {
  fillField(enSel, limitAndCleanEN(pickRandom(enPool), enLim));
  fillField(thSel, limitAndCleanTH(pickRandom(thPool), thLim));
};

const randInt = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1)) + min;
const randomInt = (min: number, max: number) => Math.floor(Math.random() * (max - min + 1)) + min;

// ==========================================
// 🔹 DATA POOL (ข้อความคงเดิม 100% จัดรูปแบบให้กระชับ)
// ==========================================
export const createPOWordingPools = (
  projectName: string, poName: string, Module: string, PriceType: string, subModule?: string
) => {
  const p = projectName || `${Module} ${PriceType}`;
  const po = poName || 'Product Offering';
  const mod = Module || 'MOB';
  const sm = subModule || 'POST';

  const modName = { MOB: { EN: 'Mobile', TH: 'มือถือ' }, ENTER: { EN: 'Entertainment', TH: 'บันเทิง' }, MUSIC: { EN: 'Music', TH: 'เพลง' }, FBB: { EN: 'Fiber Broadband', TH: 'ไฟเบอร์บรอดแบนด์' }, Fixline: { EN: 'Fixed Line', TH: 'โทรศัพท์บ้าน' } }[mod] || { EN: mod, TH: mod };
  const ptName = { onetime: { EN: 'One-Time', TH: 'ครั้งเดียว' }, recurring: { EN: 'Recurring', TH: 'รายเดือน' }, usage: { EN: 'Usage', TH: 'ตามการใช้งาน' } }[PriceType] || { EN: PriceType, TH: PriceType };

  const dataAmount = pickRandom(['10GB', '30GB', '50GB', '100GB', '200GB', '300GB', '500GB', 'Unlimited']);
  const speed = pickRandom(['100 Mbps', '300 Mbps', '500 Mbps', '1 Gbps', '2 Gbps', '5G Max']);
  const price = randomInt(199, 2999);
  const discount = pickRandom([10, 15, 20, 25, 30, 40, 50]);
  const validity = pickRandom([1, 3, 7, 30, 90, 180, 365]);
  const contractMonths = pickRandom([1, 3, 6, 12, 24, 36]);
  const benefit1 = pickRandom(['5G Access', 'Unlimited Calls', 'Free Streaming', 'Rollover Data', 'Family Sharing', 'International Roaming']);
  const benefit1TH = pickRandom(['เข้าใช้ 5G', 'โทรฟรีไม่อั้น', 'สตรีมมิ่งฟรี', 'ยกยอดเน็ต', 'แชร์ครอบครัว', 'โรมมิ่ง']);
  const benefit2 = pickRandom(['No Contract', 'Free SIM', 'eSIM Ready', 'Priority Support', 'Device Discount', 'Cashback']);
  const benefit2TH = pickRandom(['ไม่มีสัญญา', 'ซิมฟรี', 'พร้อม eSIM', 'บริการพิเศษ', 'ส่วนลดเครื่อง', 'เงินคืน']);

  return {
    shortPromotionName: { EN: [`${p} Value Pack`, `${p} Smart Deal`, `${p} Power Plan`, `${p} Daily Deal`, `${p} Big Save`, `${p} Speed Pack`, `${p} Data King`, `${p} Net Plus`, `${p} Always On`, `${p} Full Power`, `${p} Next Level`, `${p} My Choice`, `${p} Go Extra`, `${p} Double Up`, `${p} Hero`, `${p} Ace`, `${p} Edge`, `${p} Flex`, `${p} Rise`, `${p} Zone`, `${p} Core Plus`, `${p} Super Plan`, `${p} Fast Lane`, `${p} All Day`, `${p} Family Plan`, `${p} Business Pack`, `${p} Weekend Pick`, `${p} Monthly Star`, `${p} Top Value`, `${p} Best Buy`], TH: [`${p} แพ็กคุ้ม`, `${p} ดีลฉลาด`, `${p} พลานพาวเวอร์`, `${p} ดีลรายวัน`, `${p} ประหยัดสุด`, `${p} แพ็กความเร็ว`, `${p} ดาต้าคิง`, `${p} เน็ตพลัส`, `${p} ออนตลอด`, `${p} พลังเต็ม`, `${p} ขั้นต่อไป`, `${p} ของฉัน`, `${p} โกเอ็กซ์ตร้า`, `${p} ดับเบิลอัป`, `${p} ฮีโร่`, `${p} เอซ`, `${p} เอดจ์`, `${p} เฟล็กซ์`, `${p} ไรส์`, `${p} โซน`, `${p} คอร์พลัส`, `${p} ซูเปอร์แพลน`, `${p} เลนเร็ว`, `${p} ตลอดวัน`, `${p} แพลนครอบครัว`, `${p} แพ็กธุรกิจ`, `${p} พิเศษวีคเอนด์`, `${p} สตาร์ประจำเดือน`, `${p} คุ้มสุดคุ้ม`, `${p} ซื้อดีที่สุด`] },
    promotionDescription: { EN: [`Sign up for ${p} and get ${dataAmount} of data at ${speed} plus unlimited calls for just ${price} THB per month`, `${p} is the ${modName.EN} package that gives you ${dataAmount} data ${speed} speeds and ${benefit1} all in one`, `Get more done every day with ${p} featuring ${dataAmount} data at ${speed} and ${benefit2} included`, `${p} is your complete ${modName.EN} solution with ${dataAmount} data unlimited calls and 5G access at ${price} THB`, `Try ${p} and enjoy ${dataAmount} high speed data plus ${benefit1} and ${benefit2} for only ${price} THB monthly`, `${p} gives you ${dataAmount} of ${modName.EN} data at ${speed} so you never slow down`, `Choose ${p} for ${dataAmount} data ${speed} connectivity and top features at just ${price} THB a month`, `Stay connected with ${p} and enjoy ${dataAmount} data ${benefit1} and unlimited domestic calls all day`, `${p} is built for modern users offering ${dataAmount} data at ${speed} plus ${benefit1} and ${benefit2}`], TH: [`สมัคร ${p} รับเน็ต ${dataAmount} ความเร็ว ${speed} พร้อมโทรฟรีไม่จำกัดในราคาเพียง ${price} บาทต่อเดือน`, `${p} คือแพ็กเกจ${modName.TH}ที่มอบเน็ต ${dataAmount} ความเร็ว ${speed} และ${benefit1TH}ครบในที่เดียว`, `ทำได้มากขึ้นทุกวันด้วย ${p} ที่มีเน็ต ${dataAmount} ความเร็ว ${speed} และ${benefit2TH}รวมไว้แล้ว`, `${p} คือโซลูชัน${modName.TH}ครบวงจรด้วยเน็ต ${dataAmount} โทรฟรีไม่จำกัด และ 5G ที่ ${price} บาท`, `ลอง ${p} และเพลิดเพลินกับเน็ตความเร็วสูง ${dataAmount} พร้อม${benefit1TH}และ${benefit2TH}เพียง ${price} บาทต่อเดือน`, `${p} มอบเน็ต${modName.TH} ${dataAmount} ที่ความเร็ว ${speed} ทำให้คุณไม่มีวันช้าลง`, `เลือก ${p} สำหรับเน็ต ${dataAmount} การเชื่อมต่อ ${speed} และฟีเจอร์ชั้นยอดในราคาเพียง ${price} บาทต่อเดือน`, `เชื่อมต่อกับ ${p} และเพลิดเพลินกับเน็ต ${dataAmount} ${benefit1TH} และโทรฟรีไม่จำกัดตลอดวัน`, `${p} สร้างมาสำหรับผู้ใช้ยุคใหม่ มอบเน็ต ${dataAmount} ที่ความเร็ว ${speed} พร้อม${benefit1TH}และ${benefit2TH}`] },
    greetingLetter: { EN: [`Dear customer we are glad to confirm that your ${p} subscription is now active and ready to use`, `Hello and welcome to ${p} your ${modName.EN} package is live and all features are available to you`, `Dear valued customer your ${p} plan has been successfully activated with ${dataAmount} of data ready for you`, `Welcome to the ${p} family we are thrilled to have you and hope you enjoy every benefit included`, `Dear customer your ${p} subscription has been confirmed and your ${dataAmount} data at ${speed} is now ready`], TH: [`เรียนลูกค้า เรายินดียืนยันว่าการสมัคร ${p} ของคุณพร้อมใช้งานแล้ว`, `สวัสดีและยินดีต้อนรับสู่ ${p} แพ็กเกจ${modName.TH}ของคุณมีผลแล้วและฟีเจอร์ทั้งหมดพร้อมใช้`, `เรียนลูกค้าที่มีคุณค่า แผน ${p} ของคุณถูกเปิดใช้งานสำเร็จพร้อมเน็ต ${dataAmount} รอคุณอยู่`, `ยินดีต้อนรับสู่ครอบครัว ${p} เรารู้สึกตื่นเต้นที่มีคุณอยู่ด้วยและหวังว่าคุณจะสนุกกับทุกสิทธิพิเศษ`, `เรียนลูกค้า การสมัคร ${p} ของคุณได้รับการยืนยันแล้ว เน็ต ${dataAmount} ที่ความเร็ว ${speed} พร้อมแล้ว`] },
    yourPackageName: { EN: [`Your plan: ${p}`, `Currently on: ${p}`, `Active subscription: ${p}`, `Subscribed plan: ${p}`, `Running package: ${p}`, `Now on: ${p}`, `Package in use: ${p}`, `My plan: ${p}`, `Signed up for: ${p}`, `Live package: ${p}`, `Enrolled plan: ${p}`, `Chosen package: ${p}`, `${p} is active`, `${p} ${dataAmount} plan`, `${p} ${modName.EN} ${ptName.EN} active`], TH: [`แผนของคุณ: ${p}`, `ใช้งานอยู่: ${p}`, `การสมัครที่ใช้งาน: ${p}`, `แผนที่สมัคร: ${p}`, `แพ็กเกจที่รัน: ${p}`, `ตอนนี้ใช้: ${p}`, `แพ็กเกจที่ใช้: ${p}`, `แผนของฉัน: ${p}`, `สมัครอยู่กับ: ${p}`, `แพ็กเกจที่มีผล: ${p}`, `แผนที่ลงทะเบียน: ${p}`, `แพ็กเกจที่เลือก: ${p}`, `${p} ใช้งานอยู่`, `${p} แผน ${dataAmount}`, `${p} ${modName.TH} ${ptName.TH} ใช้งานอยู่`] },
    smsGreeting: { EN: [`Welcome to ${p} your package is now active and ready`, `You have joined ${p} enjoy ${dataAmount} data starting today`, `${p} is now on enjoy your ${modName.EN} benefits`, `Your ${p} plan is live and all features are unlocked`, `Thanks for choosing ${p} enjoy ${dataAmount} at ${speed}`], TH: [`ยินดีต้อนรับสู่ ${p} แพ็กเกจของคุณพร้อมใช้งานแล้ว`, `คุณเข้าร่วม ${p} แล้ว เพลิดเพลินกับเน็ต ${dataAmount} ตั้งแต่วันนี้`, `${p} เปิดแล้ว เพลิดเพลินกับสิทธิพิเศษ${modName.TH}ของคุณ`, `แผน ${p} ของคุณมีผลแล้วและฟีเจอร์ทั้งหมดพร้อมใช้`, `ขอบคุณที่เลือก ${p} เพลิดเพลินกับ ${dataAmount} ที่ ${speed}`] },
    smsDelete: { EN: [`Your ${p} package has been cancelled thank you for using our service`, `${p} has been removed from your number we hope to see you again`, `Your ${p} plan is now deactivated thank you for being with us`, `We have cancelled ${p} on your account thank you for your loyalty`, `${p} has been successfully unsubscribed we value your time with us`], TH: [`แพ็กเกจ ${p} ของคุณถูกยกเลิกแล้ว ขอบคุณที่ใช้บริการของเรา`, `${p} ถูกลบออกจากเบอร์ของคุณแล้ว หวังว่าจะพบกันใหม่`, `แผน ${p} ของคุณถูกปิดใช้งานแล้ว ขอบคุณที่อยู่กับเรา`, `เราได้ยกเลิก ${p} บนบัญชีของคุณแล้ว ขอบคุณสำหรับความไว้วางใจ`, `${p} ถูกยกเลิกสำเร็จแล้ว เราขอบคุณในทุกช่วงเวลาที่ผ่านมา`] },
    wordingInStatement: { EN: [`${p} ${modName.EN} ${ptName.EN} monthly charge`, `${p} data package ${dataAmount} at ${speed}`, `${p} subscription ${price} THB`, `Monthly fee ${p}`, `${p} service charge`, `${p} billing ${price} THB per month`, `${p} ${ptName.EN} plan charge`, `Payment for ${p}`, `${p} plan ${dataAmount} monthly`, `${p} subscription fee ${price} THB`], TH: [`ค่าบริการรายเดือน ${p} ${modName.TH} ${ptName.TH}`, `แพ็กเกจเน็ต ${p} ${dataAmount} ที่ ${speed}`, `การสมัคร ${p} ${price} บาท`, `ค่าบริการรายเดือน ${p}`, `ค่าบริการ ${p}`, `การเรียกเก็บเงิน ${p} ${price} บาทต่อเดือน`, `ค่าบริการแผน ${p} ${ptName.TH}`, `ชำระเงินสำหรับ ${p}`, `แผน ${p} ${dataAmount} รายเดือน`, `ค่าสมัคร ${p} ${price} บาท`] },
    description: { EN: [`${p} is a ${ptName.EN} ${modName.EN} package with ${dataAmount} data ${speed} speeds and unlimited domestic calls`, `${p} offers ${dataAmount} of high speed ${modName.EN} data at ${speed} including ${benefit1} and ${benefit2}`, `${p} is the ${ptName.EN} plan for modern users delivering ${dataAmount} data ${speed} and 5G access`, `${p} provides ${dataAmount} data at ${speed} plus unlimited calls and premium features for ${price} THB monthly`, `${p} is a ${modName.EN} package designed to give you ${dataAmount} data ${benefit1} and ${benefit2} at great value`], TH: [`${p} คือแพ็กเกจ${modName.TH}แบบ${ptName.TH}ด้วยเน็ต ${dataAmount} ความเร็ว ${speed} และโทรฟรีทุกเครือข่ายไม่จำกัด`, `${p} มอบเน็ต${modName.TH}ความเร็วสูง ${dataAmount} ที่ ${speed} รวมถึง${benefit1TH}และ${benefit2TH}`, `${p} คือแผน${ptName.TH}สำหรับผู้ใช้ยุคใหม่ มอบเน็ต ${dataAmount} ความเร็ว ${speed} และการเข้าถึง 5G`, `${p} มอบเน็ต ${dataAmount} ที่ ${speed} พร้อมโทรฟรีไม่จำกัดและฟีเจอร์พรีเมียมในราคา ${price} บาทต่อเดือน`, `${p} คือแพ็กเกจ${modName.TH}ที่ออกแบบมาเพื่อมอบเน็ต ${dataAmount} ${benefit1TH}และ${benefit2TH}ในราคาที่คุ้มค่า`] },
    otherCondition: { EN: [`Promotion is valid for new ${modName.EN} customers only`, `This offer is available for a limited time only`, `Valid for ${validity} days from the date of activation`, `Fair usage policy applies once the ${dataAmount} data limit is reached`, `This promotion cannot be combined with any other offer`, `Subject to credit check and approval`, `Auto renews each month unless cancelled before the renewal date`, `Terms and conditions of this promotion apply`, `Available to Thai nationals and residents only`, `Minimum contract period of ${contractMonths} months applies`], TH: [`โปรโมชันสำหรับลูกค้า${modName.TH}ใหม่เท่านั้น`, `ข้อเสนอนี้มีระยะเวลาจำกัดเท่านั้น`, `มีอายุ ${validity} วันนับจากวันที่เปิดใช้งาน`, `นโยบายการใช้งานที่เหมาะสมมีผลเมื่อใช้เน็ตครบ ${dataAmount}`, `โปรโมชันนี้ไม่สามารถใช้ร่วมกับข้อเสนออื่นได้`, `ขึ้นอยู่กับการตรวจสอบและอนุมัติเครดิต`, `ต่ออายุอัตโนมัติทุกเดือนหากไม่ยกเลิกก่อนวันต่ออายุ`, `ข้อกำหนดและเงื่อนไขของโปรโมชันนี้มีผลบังคับใช้`, `สำหรับบุคคลสัญชาติไทยและผู้มีถิ่นพำนักในประเทศไทยเท่านั้น`, `มีระยะสัญญาขั้นต่ำ ${contractMonths} เดือน`] },
    memoDescription: { EN: [`${p} internal configuration notes for reference and validation`, `${p} ${modName.EN} ${ptName.EN} setup memo PO ${po}`, `Product parameters: ${dataAmount} data at ${speed} price ${price} THB`, `${p} created for system testing and quality validation`, `Memo: ${p} configuration completed with standard settings`], TH: [`บันทึกการกำหนดค่าภายในสำหรับ ${p} เพื่อใช้อ้างอิงและตรวจสอบ`, `บันทึกการตั้งค่า ${p} ${modName.TH} ${ptName.TH} PO ${po}`, `พารามิเตอร์ผลิตภัณฑ์: เน็ต ${dataAmount} ที่ ${speed} ราคา ${price} บาท`, `${p} สร้างขึ้นเพื่อการทดสอบระบบและการตรวจสอบคุณภาพ`, `บันทึก: การกำหนดค่า ${p} เสร็จสมบูรณ์ด้วยการตั้งค่ามาตรฐาน`] },
    discountName: { EN: [`${p} New Member Discount`, `${p} Loyalty Reward`, `${p} Activation Saving`, `${p} Early Bird Saving`, `${p} Seasonal Offer`, `${p} Bundle Saving`, `${p} Data Bonus`, `${p} Speed Upgrade`, `${p} Referral Reward`, `${p} Renewal Discount`], TH: [`ส่วนลดสมาชิกใหม่ ${p}`, `รางวัลความภักดี ${p}`, `ส่วนลดเปิดใช้งาน ${p}`, `ส่วนลดจองล่วงหน้า ${p}`, `ข้อเสนอตามฤดูกาล ${p}`, `ประหยัดจากบันเดิล ${p}`, `โบนัสเน็ต ${p}`, `อัปเกรดความเร็ว ${p}`, `รางวัลแนะนำเพื่อน ${p}`, `ส่วนลดต่ออายุ ${p}`] }
  };
};

